### ISSUE TITLE
Skiss sida 1, Sammanfattande jobb information

### ISSUE THREAD

**Issue by Zexuz** [Zexuz/ABF#12]
Det behövs en skiss eller idé om hur den sammanfattande jobb sidan ska se ut. (Lista?, rutnät?, etc)

Kolla kraven som finns för projektet i [README.md](https://github.com/Zexuz/ABF/blob/master/README.md).

**Comment by davidtar1** [comment]
![abf skiss](https://cloud.githubusercontent.com/assets/14992545/15284935/bb6e016e-1b54-11e6-9d9e-64b1b466e240.png)
