### ISSUE TITLE
Skiss sida 2, Detaljerad jobb information

### ISSUE THREAD

**Issue by Zexuz** [Zexuz/ABF#13]
Vi behöver en skiss på hur den hela jobb informations sidan ska se ut. 

Kolla kraven som finns för projektet i [README.md](https://github.com/Zexuz/ABF/blob/master/README.md).

**Comment by davidtar1** [comment]
![abf skiss 2](https://cloud.githubusercontent.com/assets/14992545/15386406/fe75b880-1da7-11e6-9dea-0c3fb35cc97a.png)
